### PR TITLE
Fix python2\3 compatibility

### PR DESCRIPTION
**Pull request by sbsa**

### CODE REVIEW

**Comment by fxthomas** [comment]
Just stumbled onto this while looking for a solution with Python 3, thanks for pointing me to the right track!

I wasn't able to find docs on this other than the source code, but Zabbix Sender appears to use a binary protocol. This is why I'm a bit unsure about decoding and encoding `unicode` strings everywhere to "fix" unicode issues. JSON does use UTF-8, so it makes sense to `decode`/`encode` there, but using `bytes` everywhere else seems much cleaner to me and clearly distinguishes between what is send over the socket and real, actual data.

Would you be okay if I made a PR later with my own version of this?

**Comment by sbsa** [comment]
Ok

**Comment by jonathansp** [comment]
@sbsa @fxthomas any news?

**Comment by fxthomas** [comment]
Sorry, totally forgot that this was lying on my server. I created #22 with what I have been using.

**Comment by maksim77** [comment]
Just checked ZabbixSender work in Python versions 2 and 3. Works everywhere. Probably should close this PR?

**Comment by maksim77** [comment]
Just checked ZabbixSender work in Python versions 2 and 3. Works everywhere. Probably should close this PR?

**Comment by blacked** [comment]
Fixed [here](https://github.com/blacked/py-zabbix/pull/32) and [here](https://github.com/blacked/py-zabbix/pull/22)

**Pull request closed without merging**
